[config]
version_check = false

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.nwg-dock-hyprland]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.nwg-drawer]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/nwg-drawer/colors.css'

# App Themes, Uncomment to use (Warning! Matugen will have issues if apps are not installed)

# Only use if pywalfox is installed!

#[templates.pywalfox]
#input_path = '~/.config/matugen/templates/pywalfox-colors.json'
#output_path = '~/.cache/wal/colors.json'
#post_hook = 'pywalfox update'

# Only use if Discord is installed via FLATPAK alongside Vencord

#[templates.vesktop]
#input_path = '~/.config/matugen/templates/midnight-discord.css'
#output_path = '~/.var/app/com.discordapp.Discord/config/Vencord/themes/midnight-discord.css'